const data = {
  products: [
    {
      _id: "1",
      name: "Chocolate cake",
      brand: "spongey cake",
      price: 1000,
      rating: 4.5,
      numReviews: 100,
      image: "/images/Chocolate-cake-1.jpg",
      countInStock: 0,
      Description: "PRODUCT DESCRIPTION",
    },
    {
      _id: "2",
      name: "Chocolate cake",
      brand: "spongey cake",
      price: 1000,
      rating: 2.5,
      numReviews: 100,
      image: "/images/d1.jpg",
      countInStock: 2,
      Description: "PRODUCT DESCRIPTION",
    },
    {
      _id: "3",
      name: "Chocolate cake",
      brand: "spongey cake",
      price: 1000,
      rating: 1.5,
      numReviews: 100,
      image: "/images/Chocolate-cake-1.jpg",
      countInStock: 5,
      Description: "PRODUCT DESCRIPTION",
    },
    {
      _id: "4",
      name: "Chocolate cake",
      brand: "spongey cake",
      price: 1000,
      rating: 3.5,
      numReviews: 100,
      image: "/images/2.jpg",
      countInStock: 10,
      Description: "PRODUCT DESCRIPTION",
    },
    {
      _id: "5",
      name: "Chocolate cake",
      brand: "spongey cake",
      price: 1000,
      rating: 2,
      numReviews: 100,
      image: "/images/d1.jpg",
      countInStock: 10,
      Description: "PRODUCT DESCRIPTION",
    },
  ],
};

export default data;
